### ISSUE TITLE
Not getting response from server/API ! request time out. 

### ISSUE THREAD

**Issue by anishmodan** [paulsumit1993/DailyFeed#16]

**Comment by paulsumit1993** [comment]
hey, could you please elaborate on the error you are getting?

**Comment by anishmodan** [comment]
sorry paul , there was an issue with my ISP. newapi.org was not working. i got it fixed. Thanks for amazing work.

**Comment by anishmodan** [comment]
This would be useful if you wish to add news sources form all around the world. 

[](https://github.com/yavuz/news-feed-list-of-countries)

Thanks.

**Comment by anishmodan** [comment]
This would be useful if you wish to add news sources form all around the world.

https://github.com/yavuz/news-feed-list-of-countries

Thanks.

**Comment by paulsumit1993** [comment]
thanks for checking out the project, check out `master` branch for more features.
