### ISSUE TITLE
Unable to Install in my local

### ISSUE THREAD

**Issue by praveenmylavarapu** [paulsumit1993/DailyFeed#33]
It would be great if the Installation instructions in Readme are more detailed. I was following those steps but when I do pod install, I get the following error:

`[!] Unable to find a target named 'DailyFeedTests' in project 'DailyFeed.xcodeproj', did find 'DailyFeed'.
`

When I try for other branches, Xcode shows errors and warnings that it couldn't open a few files...

**Comment by paulsumit1993** [comment]
Hey @praveenmylavarapu, thanks for reporting, I removed the test target but forgot to remove the related pod dependency code from Podfile, have fixed it, please give it a shot again and let me know.
